version: '3.3'

services:
  db:
    image: mariadb:10.5
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeThisPassword
      MYSQL_DATABASE: caffshop
      MYSQL_USER: caffshop
      MYSQL_PASSWORD: changeme
    ports:
      - "33060:3306"
  
  backend:
    build: .
    depends_on:
      - db
    volumes:
      - uploads:/uploads
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      MySqlServerOptions__HOST: localhost
      MySqlServerOptions__NAME: caffshop
      MySqlServerOptions__USER: caffshop
      MySqlServerOptions__PASS: changeme
      MySqlServerOptions__PORT: 33060
      MySqlServerOptions__DoMigration": true
      JwtOptions__Secret: changethissecrettoo
      JwtOptions__Issuer: TymrBackend
      JwtOptions__LifeTimeMinutes: "120"
      Upload__UploadBaseDir: "/uploads"
      Upload__TempDirPath: "/tmp"
      #Upload__PrevDirPath: ""
      #Upload__CaffDirPath: ""
      #CAFF_PARSER: MOCK
    ports:
      - "8080:80"

volumes:
  db_data: {}
  uploads: {}
